### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by corentinnormand** [Code-Bullet/TheBigCB.com#9]
Even though there is no login option of any sensitive data being requested on your website, having a nice green lock on the U RL bar is quite nice to have.

You could use this beautiful free TLS certificate generator that is [letsencrypt](https://letsencrypt.org/)

Cheers !

**Comment by GameMaster2030** [comment]
It already has HTTPS enabled, just not with autoredirect. See #1

**Comment by corentinnormand** [comment]
@GameMaster2030 oh. Alright my bad. Good work so far !
